# Generated by Django 5.2.1 on 2025-05-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0002_user_restaurant_alter_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_user.activerestaurant'),
        ),
    ]
