# Generated by Django 5.2.1 on 2025-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0003_alter_user_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='does_want_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
