# Generated by Django 5.2.1 on 2025-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0004_user_does_want_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='users', to='telegram_user.activerestaurant'),
        ),
    ]
