# Generated by Django 5.2.1 on 2025-05-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0005_remove_user_restaurant_user_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
